description: A test course for pipeline testing
llm:
  max_tokens: 15000
  model: claude-3-7-sonnet
  provider: anthropic
  temperature: 0.7
skill_level: Intermediate
target_audience: Developers
title: Test Course
