# CourseSmith Application Configuration

# Application Settings
app:
  name: "CourseSmith"
  version: "0.1.0"
  description: "AI-Powered Course Writing Assistant"
  log_level: "INFO"
  courses_directory: "courses"

# LLM Provider Settings
llm:
  default_provider: "anthropic"  # Options: anthropic, openai, ollama, lmstudio
  temperature: 0.7
  max_tokens: 4000
  
  # Model Configurations
  models:
    anthropic:
      default_model: "claude-3-7-sonnet"
      available_models:
        - "claude-3-7-sonnet"
        - "claude-3.5-sonnet-2024-10-22"
        - "claude-3.5-haiku"
    openai:
      default_model: "gpt-4o"
      available_models:
        - "gpt-4o"
        - "gpt-4-turbo"
        - "gpt-3.5-turbo"
    ollama:
      default_model: "gemma3:12b"
      available_models:
        - "gemma3:12b"
        - "codegemma:7b"
        - "phi4:latest"
    lmstudio:
      default_model: "gemma-3-12b-it-qat"
      base_url: "http://127.0.0.1:1234"
      available_models:
        - "gemma-3-12b-it-qat"

# UI Settings
ui:
  theme: "light"  # Options: light, dark
  sidebar_width: "medium"  # Options: narrow, medium, wide
  show_advanced_options: false
  markdown_preview: true
