description: A test course for pipeline testing
llm:
  max_tokens: 4000
  model: claude-3-sonnet-20240229
  provider: anthropic
  temperature: 0.7
skill_level: Intermediate
target_audience: Developers
title: Test Course
